/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Learn',
      collapsible: true,
      collapsed: false,
      items: [
        'learn/getting-started',
        {
          type: 'category',
          label: 'Platform',
          items: [
            'learn/platform-overview/README',
            'learn/platform-overview/ezchain-consensus',
            'learn/platform-overview/staking',
            'learn/platform-overview/transaction-fees'
          ],
        },
        // 'learn/ezchain-bridge-faq',
        {
          type: 'link',
          label: 'Whitepapers', 
          href: 'https://ezchain.com/white-paper.pdf', 
        },
        // {
        //   type: 'link',
        //   label: 'Audits', 
        //   href: 'https://github.com/EZChain-core/audits', 
        // }
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Release Notes',
          items: [
            'build/release-notes/ezcgo',
            // {
            //   type: 'link',
            //   label: 'EZChain Notify', 
            //   href: 'https://notify.ezchain.com/', 
            // },
          ],
        },
        {
          type: 'category',
          label: 'Tutorials',
          items: [
            'build/tutorials/README',
            {
              type: 'category',
              label: 'Platform',
              items: [
                'build/tutorials/platform/README',
                {
                  type: 'category',
                  label: 'Subnets',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'build/tutorials/platform/subnets',
                    }
                  ],
                },
                'build/tutorials/platform/create-a-local-test-network',
                'build/tutorials/platform/fuji-workflow',
                // 'build/tutorials/platform/ezchain-summit-fuji-quickstart',
                'build/tutorials/platform/fund-a-local-test-network',
                'build/tutorials/platform/integrate-exchange-with-ezchain',
                'build/tutorials/platform/launch-your-ethereum-dapp',
                'build/tutorials/platform/transfer-ezc-between-x-chain-and-c-chain',
                'build/tutorials/platform/transfer-ezc-between-x-chain-and-p-chain',
                'build/tutorials/platform/transfer-ezc-between-p-chain-and-c-chain',
                'build/tutorials/platform/adjusting-gas-price-during-high-network-activity',
                'build/tutorials/platform/sending-transactions-with-dynamic-fees-using-javascript',
              ],
            },
            // {
            //   type: 'category',
            //   label: 'Nodes and Staking',
            //   items: [
            //     {
            //       type: 'autogenerated',
            //       dirName: 'build/tutorials/nodes-and-staking',
            //     },
            //     {
            //       type: 'link',
            //       label: 'Maintain an EZChain Node', 
            //       href: 'https://youtu.be', 
            //     },
            //     {
            //       type: 'link',
            //       label: 'Run an EZChain Node and Become a Validator', 
            //       href: 'https://youtu.be', 
            //     },
            //     {
            //       type: 'link',
            //       label: 'Run an EZChain Node and Stake with the EZChain Wallet', 
            //       href: 'https://youtu.be', 
            //     },
            //   ],
            // },
            {
              type: 'category',
              label: 'Smart Contract',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'build/tutorials/smart-contracts',
                },
              ],
            },
            {
              type: 'category',
              label: 'Smart Digital Assets',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'build/tutorials/smart-digital-assets',
                },
              ],
            },
            {
              type: 'category',
              label: 'Tutorials Contest',
              items: [
                'build/tutorials/tutorials-contest/README',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'EZChainGo APIs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'build/ezcgo-apis',
            },
          ],
        },
        {
          type: 'category',
          label: 'Tools',
          items: [
            'build/tools/README',
            'build/tools/public-api',
            'build/tools/postman-ezchain-collection',
            {
              type: 'category',
              label: 'EZChainJS',
              items: [
                'build/tools/ezchainjs/README',
                'build/tools/ezchainjs/api',
                'build/tools/ezchainjs/create-an-asset-on-the-x-chain',
                'build/tools/ezchainjs/manage-x-chain-keys',
                'build/tools/ezchainjs/send-an-asset-on-the-x-chain',
              ],
            },
            {
              type: 'category',
              label: 'Wallet SDK',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'build/tools/ezchain-wallet-sdk',
                },
              ],
            },
            'build/tools/dashboards/README',
            // 'build/tools/network-runner',
            // 'build/tools/ezc-sim',
            'build/tools/abigen',
            // 'build/tools/ezcsh',
            // 'build/tools/deprecating-ortelius',
            'build/tools/ortelius',
          ],
        },
        {
          type: 'category',
          label: 'References',
          items: [
            {
              type: 'autogenerated',
              dirName: 'build/references',
            },
          ],
        },
      ],
    },
    // {
    //   type: 'link',
    //   label: 'Product Support', 
    //   href: 'https://support.ezchain.com/en/', 
    // },
  ],

};

module.exports = sidebars;
